apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1saraka-ambulance-ufe-content
spec:
  microFrontend: cv1saraka-ambulance-ufe
  element: cv1saraka-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1saraka-ambulance-wl(/.*)?$"