kind: Service
apiVersion: v1
metadata:
  name: cv1saraka-openapi-ui
spec:
  selector:
    pod: cv1saraka-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081